package main

// CacheTemplate is template for cache generation
const CacheTemplate = `// Code generated by go-gengen(v0.0.2) DO NOT EDIT.

package {{.Package}}

import ({{range .Stdlib}}
	"{{.}}"{{end}}{{if .Remote}}
{{range .Remote}}
	"{{.}}"{{end}}{{end}}
)

// Cache is an observable concurrent in-memory datastore
type Cache struct {
	dat   map[{{.Key}}]{{.Val}}
	mu    sync.Mutex
	obs   []Setter
}

// Storer is an abstraction of in-memory datastore
type Storer interface {
	Get({{.Key}}) {{.Val}}
	Set({{.Key}}, {{.Val}})
	Each(Setter)
	Sync(func(Getter, Setter))
	Keys() []{{.Key}}
	Observe(Setter)
	Remove({{.Key}})
}

// Getter is a k->v func
type Getter = func({{.Key}}) {{.Val}}

// Setter is a k,v func
type Setter = func({{.Key}}, {{.Val}})

// NewCache returns a new Cache
func NewCache() *Cache {
	return &Cache{
		dat: make(map[{{.Key}}]{{.Val}}),
		obs:   make([]Setter, 0),
	}
}

// Get returns the {{.Val}} for a {{.Key}}
func (c *Cache) Get(k {{.Key}}) {{.Val}} { return c.dat[k] }

// Set saves a {{.Val}} for a {{.Key}}
func (c *Cache) Set(k {{.Key}}, v {{.Val}}) {
	c.mu.Lock()
	c.set(k, v)
	c.mu.Unlock()
}

func (c *Cache) set(k {{.Key}}, v {{.Val}}) {
	if v != nil {
		c.dat[k] = v
	} else {
		delete(c.dat, k)
	}
	for _, f := range c.obs {
		f(k, v)
	}
}

// Each calls the func for each {{.Key}},{{.Val}} in this Cache
func (c *Cache) Each(f Setter) {
	c.mu.Lock()
	for k, v := range c.dat {
		f(k, v)
	}
	c.mu.Unlock()
}

// Sync calls the func within the cache lock state
func (c *Cache) Sync(f func(Getter, Setter)) {
	c.mu.Lock()
	f(c.Get, c.set)
	c.mu.Unlock()
}

// Keys returns a new slice with all the {{.Key}} keys
func (c *Cache) Keys() []{{.Key}} {
	c.mu.Lock()
	keys := make([]{{.Key}}, 0, len(c.dat))
	for k := range c.dat {
		keys = append(keys, k)
	}
	c.mu.Unlock()
	return keys
}

// Observe adds a func to be called when a {{.Val}} is explicitly set
func (c *Cache) Observe(f Setter) { c.obs = append(c.obs, f) }

// Remove deletes a {{.Key}},{{.Val}}
func (c *Cache) Remove(k {{.Key}}) { c.Set(k, nil) }
`
